---
repos:
  # See https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-case-conflict
      - id: requirements-txt-fixer
      - id: check-ast
      - id: mixed-line-ending
        args: ['--fix=lf']
#      - id: check-toml

#  - repo: https://github.com/asottile/reorder_python_imports
#    rev: v3.0.1
#    hooks:
#      - id: reorder-python-imports
#        args: [--py37-plus]
#
#  - repo: https://github.com/asottile/add-trailing-comma
#    rev: v2.2.2
#    hooks:
#      - id: add-trailing-comma
#
#  - repo: https://github.com/psf/black
#    rev: 22.3.0
#    hooks:
#      - id: black
#
#  - repo: https://github.com/PyCQA/flake8
#    rev: 4.0.1
#    hooks:
#      - id: flake8
#        args: [--config=.flake8]
#        additional_dependencies: [flake8-bugbear]
#
#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.7.1
#    hooks:
#      - id: bandit
